// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230919063154_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Action",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Thriller",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Romance",
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Auther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auther = "Poul Cohelo",
                            CategoryId = 1,
                            Description = "Best seller book of 2023",
                            ISBN = "1234",
                            ImageUrl = "",
                            ListPrice = 350.0,
                            Price = 320.0,
                            Price100 = 250.0,
                            Price50 = 300.0,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 2,
                            Auther = "Alexander",
                            CategoryId = 2,
                            Description = "Best seller book of 2022",
                            ISBN = "4321",
                            ImageUrl = "",
                            ListPrice = 250.0,
                            Price = 220.0,
                            Price100 = 150.0,
                            Price50 = 200.0,
                            Title = "Power of focus"
                        },
                        new
                        {
                            Id = 3,
                            Auther = "Robert Kiyosaki",
                            CategoryId = 3,
                            Description = "Best seller book of 2021",
                            ISBN = "1243",
                            ImageUrl = "",
                            ListPrice = 450.0,
                            Price = 420.0,
                            Price100 = 350.0,
                            Price50 = 400.0,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            Id = 4,
                            Auther = "Glenn Maxwell",
                            CategoryId = 2,
                            Description = "Best seller book of 2020",
                            ISBN = "1124",
                            ImageUrl = "",
                            ListPrice = 550.0,
                            Price = 520.0,
                            Price100 = 450.0,
                            Price50 = 500.0,
                            Title = "Hyper Focus"
                        },
                        new
                        {
                            Id = 5,
                            Auther = "Carl Neoport",
                            CategoryId = 3,
                            Description = "Best seller book of 2019",
                            ISBN = "2222",
                            ImageUrl = "",
                            ListPrice = 650.0,
                            Price = 620.0,
                            Price100 = 550.0,
                            Price50 = 600.0,
                            Title = "Deep Work"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Catgories")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catgories");
                });
#pragma warning restore 612, 618
        }
    }
}
